import './globals.css'
import React from "react";
import {Metadata} from "next";
import UI from "@/components/UI";
import Header from "@/components/Header";
import '@fortawesome/fontawesome-svg-core/styles.css'
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  creator: 'NICHOLAS AGBO',
  applicationName: 'Portfolios'
}



const font = Roboto({
  subsets: ['latin'], 
  display: 'swap', 
  weight: "500", 
  preload: true, 
  variable: "--fsText",
  fallback: ["var(--nextui-fonts-sans)"]
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
      <UI>
          <Header/>
        {children}
      </UI>
      </body>
    </html>
  )
}
