import './globals.css'
import React from "react";
import {Metadata} from "next";
import UI from "@/components/UI";
import Header from "@/components/Header";
import '@fortawesome/fontawesome-svg-core/styles.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  creator: 'NICHOLAS AGBO',
  applicationName: 'Portfolios'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <UI>
          <Header/>
        {children}
      </UI>
      </body>
    </html>
  )
}
